server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./demo_dev;MODE=MYSQL
    username: newskit
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always