server:
  shutdown: graceful
  port: 18082
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/newskit_keyword
    username: userlocal
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    level:
      org.hibernate.SQL: INFO
      org.hibernate.orm.jdbc.bind: INFO
      org.hibernate.orm.jdbc.extract: INFO
      org.springframework.transaction.interceptor: INFO

## Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://bangvelope.com/newskit/eureka
  instance:
    prefer-ip-address: true